import "./globals.css";
import { Comfortaa } from "next/font/google";

const comfortaa = Comfortaa({
  subsets: ["latin"],
  variable: "--font-comfortaa",
});

import type { Metadata } from "next";

import Header from "@/components/Header";
import Footer from "@/components/Footer";

import { client } from "@/utils/sanity";
import { footer, header, meta } from "@/utils/queries";
import urlBuilder from "@/utils/urlBuilder";

async function getFooterData() {
  const posts = await client.fetch(footer);
  return posts;
}

async function getHeaderData() {
  const posts = await client.fetch(header);
  return posts;
}

async function getMetadata() {
  const metaData = await client.fetch(meta);
  return metaData;
}

export async function generateMetadata(): Promise<Metadata> {
  const md = await getMetadata();
  return {
    title: md.siteTitle,
    description: md.siteDescription,
    openGraph: {
      title: md.siteTitle,
      description: md.siteDescription,
      url: "https://solify.com",
      siteName: "Next.js",
      images: [
        {
          url: urlBuilder(md.sharingImage.asset).width(800).height(600).url(),
          width: 800,
          height: 600,
        },
      ],
      locale: "en-GB",
      type: "website",
    },
    twitter: {
      card: "summary_large_image",
      title: md.siteTitle,
      description: md.siteDescription,
      images: [urlBuilder(md.sharingImage.asset).width(800).height(600).url()],
    },
  };
}

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const footerData = getFooterData();
  const headerData = getHeaderData();

  // Wait for the promises to resolve
  const [footer, header] = await Promise.all([footerData, headerData]);

  return (
    <html lang="en" className={`${comfortaa.variable} font-sans`}>
      <body>
        <Header
          siteLogo={header?.siteLogo}
          siteTitle={header?.siteTitle}
          email={header?.email}
          instagramLink={header?.instagramLink}
        />
        {children}
        <Footer
          siteTitle={footer?.siteTitle}
          footerLinks={footer?.footerLinks}
        />
      </body>
    </html>
  );
}
