import "./globals.css";
import { Comfortaa } from "next/font/google";

const comfortaa = Comfortaa({
  subsets: ["latin"],
  variable: "--font-comfortaa",
});

import Header from "@/components/Header";
import Footer from "@/components/Footer";

import { client } from "@/utils/sanity";
import { footer, header } from "@/utils/queries";

async function getFooterData() {
  const posts = await client.fetch(footer);
  return posts;
}

async function getHeaderData() {
  const posts = await client.fetch(header);
  return posts;
}

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const footerData = getFooterData();
  const headerData = getHeaderData();

  // Wait for the promises to resolve
  const [footer, header] = await Promise.all([footerData, headerData]);

  return (
    <html lang="en" className={`${comfortaa.variable} font-sans`}>
      <body>
        <Header
          siteLogo={header?.siteLogo}
          siteTitle={header?.siteTitle}
          email={header?.email}
          instagramLink={header?.instagramLink}
        />
        {children}
        <Footer
          siteTitle={footer?.siteTitle}
          footerLinks={footer?.footerLinks}
        />
      </body>
    </html>
  );
}
